export const imagesData = [
  { id: 1, value: 'cat', img: 'cat.png', isOpen: false },
  { id: 2, value: 'cat', img: 'cat.png', isOpen: false },
  { id: 3, value: 'dog', img: 'dog.png', isOpen: false },
  { id: 4, value: 'dog', img: 'dog.png', isOpen: false },
  { id: 5, value: 'elephant', img: 'elephant.png', isOpen: false },
  { id: 6, value: 'elephant', img: 'elephant.png', isOpen: false },
  { id: 7, value: 'frog', img: 'frog.png', isOpen: false },
  { id: 8, value: 'frog', img: 'frog.png', isOpen: false },
  { id: 9, value: 'panda', img: 'panda.png', isOpen: false },
  { id: 10, value: 'panda', img: 'panda.png', isOpen: false },
  { id: 11, value: 'owl', img: 'owl.png', isOpen: false },
  { id: 12, value: 'owl', img: 'owl.png', isOpen: false },
  { id: 13, value: 'giraffe', img: 'giraffe.png', isOpen: false },
  { id: 14, value: 'giraffe', img: 'giraffe.png', isOpen: false },
  { id: 15, value: 'rabbit', img: 'rabbit.png', isOpen: false },
  { id: 16, value: 'rabbit', img: 'rabbit.png', isOpen: false },
];
